package component:crc-wasm;

//interface crc32-hasher {
//    resource hasher {
//        constructor();
//        update: func(input: list<u8>);
//        finalize: func() -> u32;
//        reset: func();
//    }
//}

interface crc64-nvme-hasher {
    resource hasher {
        constructor();
        update: func(input: list<u8>);
        finalize: func() -> u64;
        reset: func();
    }

}

/// An example world for the component to target.
world crc-hashers {
    //export crc32-hasher;
    export crc64-nvme-hasher;
    //export crc32-hash: func(input: list<u8>) -> u32;
    export crc64-nvme-hash: func(input: list<u8>) -> u64;
}
